//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.UI.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avertissement : Ce programme est protégè par la loi relative au droit d&apos;auteur et par les conventions internationales. Toute reproduction ou distribution partielle ou totale du logiciel, par quelque moyen que ce soit, est strictement interdite. Toute personne ne respectant pas ces dispostions se rendra coupable du délit de contrefaçon et sera passible des sanctions pénales prévues par la loi..
        /// </summary>
        public static string AboutWarning {
            get {
                return ResourceManager.GetString("AboutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au moins une règle doit être définie..
        /// </summary>
        public static string AnyRulesError {
            get {
                return ResourceManager.GetString("AnyRulesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;élément n&apos;a pas pu être copié dans le presse papier.
        ///Consulter les logs pour plus d&apos;informations..
        /// </summary>
        public static string CopyInClipBoardError {
            get {
                return ResourceManager.GetString("CopyInClipBoardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;élément à bien été copié dans le presse papier.
        ///Utiliser Ctrl+V, ou Clic droit puis Coller pour récupérer l&apos;élément..
        /// </summary>
        public static string CopyInClipBoardSuccess {
            get {
                return ResourceManager.GetString("CopyInClipBoardSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de trouver le dossier &quot;{0}&quot;..
        /// </summary>
        public static string DirectoryXNotFoundError {
            get {
                return ResourceManager.GetString("DirectoryXNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier a été téléchargé avec succès..
        /// </summary>
        public static string DownloadFileSuccess {
            get {
                return ResourceManager.GetString("DownloadFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de fin doit être supérieur ou égal à la date de début..
        /// </summary>
        public static string FieldEndDateMustBeUpperOrEqualsThanStartDateError {
            get {
                return ResourceManager.GetString("FieldEndDateMustBeUpperOrEqualsThanStartDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de fin doit être inférieur à l&apos;heure de début..
        /// </summary>
        public static string FieldEndTimeMustBeLowerThanStartTimeError {
            get {
                return ResourceManager.GetString("FieldEndTimeMustBeLowerThanStartTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de fin doit être supérieur ou égal à l&apos;heure de début..
        /// </summary>
        public static string FieldEndTimeMustBeUpperOrEqualsThanStartTimeError {
            get {
                return ResourceManager.GetString("FieldEndTimeMustBeUpperOrEqualsThanStartTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de fin doit être supérieur à l&apos;heure de début..
        /// </summary>
        public static string FieldEndTimeMustBeUpperThanStartTimeError {
            get {
                return ResourceManager.GetString("FieldEndTimeMustBeUpperThanStartTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les champs renseignés ne sont pas corrects..
        /// </summary>
        public static string FieldsInvalidError {
            get {
                return ResourceManager.GetString("FieldsInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de début doit être inférieur ou égal à la date de fin..
        /// </summary>
        public static string FieldStartDateMustBeLowerOrEqualsThanEndDateError {
            get {
                return ResourceManager.GetString("FieldStartDateMustBeLowerOrEqualsThanEndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de début doit être inférieur ou égal à l&apos;heure de fin..
        /// </summary>
        public static string FieldStartTimeMustBeLowerOrEqualsThanEndTimeError {
            get {
                return ResourceManager.GetString("FieldStartTimeMustBeLowerOrEqualsThanEndTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; est obligatoire..
        /// </summary>
        public static string FieldXIsRequiredError {
            get {
                return ResourceManager.GetString("FieldXIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; ne correspond pas à un chemin de fichier valide..
        /// </summary>
        public static string FieldXMustBeAnValidFilePathError {
            get {
                return ResourceManager.GetString("FieldXMustBeAnValidFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être compris entre {1} et {2}..
        /// </summary>
        public static string FieldXMustBeBetweenYAndZError {
            get {
                return ResourceManager.GetString("FieldXMustBeBetweenYAndZError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La collection &quot;{0}&quot; doit contenir au moins 1 élément..
        /// </summary>
        public static string FieldXMustBeContainOneItemAtLeastError {
            get {
                return ResourceManager.GetString("FieldXMustBeContainOneItemAtLeastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être différent du champ &quot;{1}&quot;..
        /// </summary>
        public static string FieldXMustBeDifferentOfFieldYError {
            get {
                return ResourceManager.GetString("FieldXMustBeDifferentOfFieldYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être dans le passé..
        /// </summary>
        public static string FieldXMustBeInPastError {
            get {
                return ResourceManager.GetString("FieldXMustBeInPastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être inférieur ou égal à {1}..
        /// </summary>
        public static string FieldXMustBeLowerOrEqualsThanYError {
            get {
                return ResourceManager.GetString("FieldXMustBeLowerOrEqualsThanYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être inférieur à {1}..
        /// </summary>
        public static string FieldXMustBeLowerThanYError {
            get {
                return ResourceManager.GetString("FieldXMustBeLowerThanYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être supérieur ou égal à {1}..
        /// </summary>
        public static string FieldXMustBeUpperOrEqualsThanYError {
            get {
                return ResourceManager.GetString("FieldXMustBeUpperOrEqualsThanYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; doit être supérieur à {1}..
        /// </summary>
        public static string FieldXMustBeUpperThanYError {
            get {
                return ResourceManager.GetString("FieldXMustBeUpperThanYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; ne correspond pas à une adresse de messagerie valide..
        /// </summary>
        public static string FieldXMustBeValidEmailAddressError {
            get {
                return ResourceManager.GetString("FieldXMustBeValidEmailAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; ne correspond pas à un numéro de téléphone valide..
        /// </summary>
        public static string FieldXMustBeValidPhoneNumberError {
            get {
                return ResourceManager.GetString("FieldXMustBeValidPhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de trouver une partie du chemin &quot;{0}&quot;..
        /// </summary>
        public static string FieldXMustContainExistingFolderError {
            get {
                return ResourceManager.GetString("FieldXMustContainExistingFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier spécifié dans le champ &quot;{0}&quot; n&apos;a pas été trouvé..
        /// </summary>
        public static string FieldXMustContainsExistingFileError {
            get {
                return ResourceManager.GetString("FieldXMustContainsExistingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &quot;{0}&quot; ne doit pas dépasser {1} caractères..
        /// </summary>
        public static string FieldXMustHaveMaxLengthYError {
            get {
                return ResourceManager.GetString("FieldXMustHaveMaxLengthYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La collection &quot;{0}&quot; ne doit pas avoir d&apos;élément identique..
        /// </summary>
        public static string FieldXMustHaveUniqueItemsError {
            get {
                return ResourceManager.GetString("FieldXMustHaveUniqueItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;extension du fichier spécifié n&apos;est pas valide..
        /// </summary>
        public static string FileHasInvalidExtensionError {
            get {
                return ResourceManager.GetString("FileHasInvalidExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier va être supprimer. Voulez-vous continuer ?.
        /// </summary>
        public static string FileRemovingQuestion {
            get {
                return ResourceManager.GetString("FileRemovingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier &quot;{0}&quot; est utilisé par un autre processus.
        /// </summary>
        public static string FileXAlreadyUsedError {
            get {
                return ResourceManager.GetString("FileXAlreadyUsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de trouver le fichier &quot;{0}&quot;..
        /// </summary>
        public static string FileXNotFoundError {
            get {
                return ResourceManager.GetString("FileXNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier &quot;{0}&quot; n&apos;a pas pu être ouvert.
        ///Consulter les logs pour plus d&apos;informations..
        /// </summary>
        public static string FileXOpenError {
            get {
                return ResourceManager.GetString("FileXOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier &quot;{0}&quot; a été supprimé avec succès..
        /// </summary>
        public static string FileXRemovedSuccess {
            get {
                return ResourceManager.GetString("FileXRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des éléments ont été modifiés. Il seront définitivement perdus. Vous-vous continuer ?.
        /// </summary>
        public static string ItemModificationCancellingQuestion {
            get {
                return ResourceManager.GetString("ItemModificationCancellingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des éléments ont été modifiés. Voulez vous les sauvegarder ?.
        /// </summary>
        public static string ItemSavingQuestion {
            get {
                return ResourceManager.GetString("ItemSavingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;élément &quot;{0}&quot; n&apos;a pas été trouvé&quot;..
        /// </summary>
        public static string ItemXNotFoundException {
            get {
                return ResourceManager.GetString("ItemXNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;espace disque est insuffisant pour effectuer l&apos;oppération..
        /// </summary>
        public static string NotEnoughSpaceDisk {
            get {
                return ResourceManager.GetString("NotEnoughSpaceDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur inattendue est survenue : {0}.
        /// </summary>
        public static string UnexpectedXError {
            get {
                return ResourceManager.GetString("UnexpectedXError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 élément a été ajoutée..
        /// </summary>
        public static string XItemsAddedSuccess {
            get {
                return ResourceManager.GetString("XItemsAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # éléments ont été ajoutées..
        /// </summary>
        public static string XItemsAddedSuccessPlural {
            get {
                return ResourceManager.GetString("XItemsAddedSuccessPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # élément a été modifié..
        /// </summary>
        public static string XItemsHasBeenModifiedSuccess {
            get {
                return ResourceManager.GetString("XItemsHasBeenModifiedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # éléments ont été modifiés..
        /// </summary>
        public static string XItemsHasBeenModifiedSuccessPlural {
            get {
                return ResourceManager.GetString("XItemsHasBeenModifiedSuccessPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de supprimer définitivement un élément. Voulez-vous continuer ?.
        /// </summary>
        public static string XItemsRemovingQuestion {
            get {
                return ResourceManager.GetString("XItemsRemovingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de supprimer définitivement # éléments. Voulez-vous continuer ?.
        /// </summary>
        public static string XItemsRemovingQuestionPlural {
            get {
                return ResourceManager.GetString("XItemsRemovingQuestionPlural", resourceCulture);
            }
        }
    }
}
