//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNet.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNet.UI.Resources.UiResources", typeof(UiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Propos.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Propos de {0}.
        /// </summary>
        public static string AboutX {
            get {
                return ResourceManager.GetString("AboutX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un filtre.
        /// </summary>
        public static string AddFilter {
            get {
                return ResourceManager.GetString("AddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter le groupe.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout multiple.
        /// </summary>
        public static string AddMultiple {
            get {
                return ResourceManager.GetString("AddMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter le tri.
        /// </summary>
        public static string AddSort {
            get {
                return ResourceManager.GetString("AddSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtres avancés.
        /// </summary>
        public static string AdvancedFilters {
            get {
                return ResourceManager.GetString("AdvancedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toute.
        /// </summary>
        public static string AllFemale {
            get {
                return ResourceManager.GetString("AllFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes.
        /// </summary>
        public static string AllFemales {
            get {
                return ResourceManager.GetString("AllFemales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les fichiers.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string AllImages {
            get {
                return ResourceManager.GetString("AllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout.
        /// </summary>
        public static string AllMale {
            get {
                return ResourceManager.GetString("AllMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        public static string AllMales {
            get {
                return ResourceManager.GetString("AllMales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Et.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatique.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur de fond.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par {0}.
        /// </summary>
        public static string ByX {
            get {
                return ResourceManager.GetString("ByX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensible à la casse.
        /// </summary>
        public static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer tout.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer les filtres.
        /// </summary>
        public static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer la sélection.
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer tout.
        /// </summary>
        public static string CloseAll {
            get {
                return ResourceManager.GetString("CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer les autres éléments.
        /// </summary>
        public static string CloseAllButThis {
            get {
                return ResourceManager.GetString("CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier dans le presse-papier.
        /// </summary>
        public static string CopyInClipBoard {
            get {
                return ResourceManager.GetString("CopyInClipBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé le.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé par.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création.
        /// </summary>
        public static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couper.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sombre.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactivé(e).
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affichage.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout afficher.
        /// </summary>
        public static string DisplayAll {
            get {
                return ResourceManager.GetString("DisplayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affichage Liste.
        /// </summary>
        public static string DisplayList {
            get {
                return ResourceManager.GetString("DisplayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affichage Calendrier.
        /// </summary>
        public static string DisplayScheduler {
            get {
                return ResourceManager.GetString("DisplayScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargement.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier a été téléchargé avec succès..
        /// </summary>
        public static string DownloadFileSuccess {
            get {
                return ResourceManager.GetString("DownloadFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition de # élément.
        /// </summary>
        public static string EditionOfXItems {
            get {
                return ResourceManager.GetString("EditionOfXItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition de # éléments.
        /// </summary>
        public static string EditionOfXItemsPlural {
            get {
                return ResourceManager.GetString("EditionOfXItemsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activé(e).
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur(s).
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image BMP.
        /// </summary>
        public static string FileBmp {
            get {
                return ResourceManager.GetString("FileBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV (délimiteur : point-virgule).
        /// </summary>
        public static string FileCsv {
            get {
                return ResourceManager.GetString("FileCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classeur Excel.
        /// </summary>
        public static string FileExcel {
            get {
                return ResourceManager.GetString("FileExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image GIF.
        /// </summary>
        public static string FileGif {
            get {
                return ResourceManager.GetString("FileGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icône.
        /// </summary>
        public static string FileIco {
            get {
                return ResourceManager.GetString("FileIco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image JPEG.
        /// </summary>
        public static string FileJpeg {
            get {
                return ResourceManager.GetString("FileJpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image JPG.
        /// </summary>
        public static string FileJpg {
            get {
                return ResourceManager.GetString("FileJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image PNG.
        /// </summary>
        public static string FilePng {
            get {
                return ResourceManager.GetString("FilePng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image TIF.
        /// </summary>
        public static string FileTif {
            get {
                return ResourceManager.GetString("FileTif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrer.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtres.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur du texte.
        /// </summary>
        public static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du.
        /// </summary>
        public static string From1 {
            get {
                return ResourceManager.GetString("From1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouper.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouper par.
        /// </summary>
        public static string GroupBy {
            get {
                return ResourceManager.GetString("GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cacher les filtres.
        /// </summary>
        public static string HideFilters {
            get {
                return ResourceManager.GetString("HideFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cacher le mot de passe.
        /// </summary>
        public static string HidePassword {
            get {
                return ResourceManager.GetString("HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icône.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorer.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout ignorer.
        /// </summary>
        public static string IgnoreAll {
            get {
                return ResourceManager.GetString("IgnoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppr.
        /// </summary>
        public static string InputDelete {
            get {
                return ResourceManager.GetString("InputDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est.
        /// </summary>
        public static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elément.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eléments.
        /// </summary>
        public static string ItemPlural {
            get {
                return ResourceManager.GetString("ItemPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to éléments par page.
        /// </summary>
        public static string ItemsByPage {
            get {
                return ResourceManager.GetString("ItemsByPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elément.
        /// </summary>
        public static string ItemZero {
            get {
                return ResourceManager.GetString("ItemZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langage.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernier accès le.
        /// </summary>
        public static string LastAccessAt {
            get {
                return ResourceManager.GetString("LastAccessAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clair.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement des données....
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuel.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrandir.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réduire.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifié le.
        /// </summary>
        public static string ModifiedAt {
            get {
                return ResourceManager.GetString("ModifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifié par.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer vers le bas.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer vers le haut.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacer vers.
        /// </summary>
        public static string MovingTo {
            get {
                return ResourceManager.GetString("MovingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Valeurs multiples).
        /// </summary>
        public static string MultiplePlaceHolder {
            get {
                return ResourceManager.GetString("MultiplePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page suivante.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a aucune donnée pour le moment.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune modification.
        /// </summary>
        public static string NoModifications {
            get {
                return ResourceManager.GetString("NoModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun(e).
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        public static string NoneFemale {
            get {
                return ResourceManager.GetString("NoneFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string NoneMale {
            get {
                return ResourceManager.GetString("NoneMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun résultat.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pas de suggestions).
        /// </summary>
        public static string NoSpellSuggestions {
            get {
                return ResourceManager.GetString("NoSpellSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le client de messagerie.
        /// </summary>
        public static string OpenMailClient {
            get {
                return ResourceManager.GetString("OpenMailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coller.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epinglé(s).
        /// </summary>
        public static string PinnedPlural {
            get {
                return ResourceManager.GetString("PinnedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préférences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperçu.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page précédente.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriétés.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récent(s).
        /// </summary>
        public static string Recents {
            get {
                return ResourceManager.GetString("Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rétablir.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraîchir.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recharger.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le groupe.
        /// </summary>
        public static string RemoveGroup {
            get {
                return ResourceManager.GetString("RemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le tri.
        /// </summary>
        public static string RemoveSort {
            get {
                return ResourceManager.GetString("RemoveSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression.
        /// </summary>
        public static string Removing {
            get {
                return ResourceManager.GetString("Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurer.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Révéler le mot de passe.
        /// </summary>
        public static string RevealPassword {
            get {
                return ResourceManager.GetString("RevealPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout sauvegarder.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder sous.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir l&apos;élément.
        /// </summary>
        public static string SeeItem {
            get {
                return ResourceManager.GetString("SeeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout sélectionner.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionné.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnés.
        /// </summary>
        public static string SelectedPlural {
            get {
                return ResourceManager.GetString("SelectedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un élément.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner des éléments.
        /// </summary>
        public static string SelectItems {
            get {
                return ResourceManager.GetString("SelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un mail.
        /// </summary>
        public static string SendMail {
            get {
                return ResourceManager.GetString("SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les colonnes.
        /// </summary>
        public static string ShowColumns {
            get {
                return ResourceManager.GetString("ShowColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les filtres.
        /// </summary>
        public static string ShowFilters {
            get {
                return ResourceManager.GetString("ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trier.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trier par.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtres rapides.
        /// </summary>
        public static string SpeedFilters {
            get {
                return ResourceManager.GetString("SpeedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        public static string SpellChecking {
            get {
                return ResourceManager.GetString("SpellChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succès.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverser le tri.
        /// </summary>
        public static string SwitchSort {
            get {
                return ResourceManager.GetString("SwitchSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Système.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texte.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Au.
        /// </summary>
        public static string To1 {
            get {
                return ResourceManager.GetString("To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aujourd&apos;hui.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non défini(e).
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non définie.
        /// </summary>
        public static string UndefinedFemale {
            get {
                return ResourceManager.GetString("UndefinedFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non défini.
        /// </summary>
        public static string UndefinedMale {
            get {
                return ResourceManager.GetString("UndefinedMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non définies.
        /// </summary>
        public static string UndefinedPluralFemale {
            get {
                return ResourceManager.GetString("UndefinedPluralFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non défini(e)s.
        /// </summary>
        public static string UndefiniedPlural {
            get {
                return ResourceManager.GetString("UndefiniedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non définis.
        /// </summary>
        public static string UndefiniedPluralMale {
            get {
                return ResourceManager.GetString("UndefiniedPluralMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu(e).
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnue.
        /// </summary>
        public static string UnknownFemale {
            get {
                return ResourceManager.GetString("UnknownFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        public static string UnknownMale {
            get {
                return ResourceManager.GetString("UnknownMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désélectionner.
        /// </summary>
        public static string Unselect {
            get {
                return ResourceManager.GetString("Unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout désélectionner.
        /// </summary>
        public static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.{0}.
        /// </summary>
        public static string VersionAbbrX {
            get {
                return ResourceManager.GetString("VersionAbbrX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vues.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largeur.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecrire.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # élément.
        /// </summary>
        public static string XItems {
            get {
                return ResourceManager.GetString("XItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # éléments.
        /// </summary>
        public static string XItemsPlural {
            get {
                return ResourceManager.GetString("XItemsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 élément.
        /// </summary>
        public static string XItemsZero {
            get {
                return ResourceManager.GetString("XItemsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # sélectionné.
        /// </summary>
        public static string XSelected {
            get {
                return ResourceManager.GetString("XSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # élément sélectionné.
        /// </summary>
        public static string XSelectedItems {
            get {
                return ResourceManager.GetString("XSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # éléments sélectionnés.
        /// </summary>
        public static string XSelectedItemsPlural {
            get {
                return ResourceManager.GetString("XSelectedItemsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun élément sélectionné.
        /// </summary>
        public static string XSelectedItemsZero {
            get {
                return ResourceManager.GetString("XSelectedItemsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # sélectionnés.
        /// </summary>
        public static string XSelectedPlural {
            get {
                return ResourceManager.GetString("XSelectedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun sélectionné.
        /// </summary>
        public static string XSelectedZero {
            get {
                return ResourceManager.GetString("XSelectedZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
